# Generated by Django 5.0.7 on 2024-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='billing_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='billing',
            name='sale_number',
            field=models.IntegerField(null=True),
        ),
    ]
