# Generated by Django 5.0.7 on 2024-07-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0008_alter_billing_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
