# Generated by Django 5.0.7 on 2024-07-21 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0009_alter_billing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='sale_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
