# Generated by Django 5.0.7 on 2024-07-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0002_rename_billing_id_billing_id_billing_sale_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
