# Generated by Django 5.0.7 on 2024-07-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0004_billing_purchasetime_product_expirydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expirydate',
            new_name='manufacturingdate',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
