# Generated by Django 5.0.7 on 2024-07-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0005_rename_expirydate_product_manufacturingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
