# Generated by Django 5.0.7 on 2024-07-21 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0006_rename_product_name_billing_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='sale_number',
            field=models.IntegerField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
