# Generated by Django 5.0.7 on 2024-07-22 01:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystemapp', '0010_alter_billing_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='sale_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('sale_number', 'product_id')},
        ),
    ]
